language: csharp
dotnet: 2.1.402
node_js: "10"
mono: none
os: osx
env:
  - DISABLE_EXTERNAL_PARALLEL_TESTS=true
install:
  - npm install -g ganache-cli
script:
  - dotnet restore --configfile Nuget.Config
  - dotnet msbuild -p:Configuration=Debug /maxcpucount:1 /nodeReuse:false
  - dotnet test -c Debug --no-build --no-restore